name: VPN

services:
    vpn:
        image: qmcgaw/gluetun
        container_name: vpn
        restart: unless-stopped
        cap_add:
            - NET_ADMIN # This needed for vpn to modify network traffic
        devices:
            - /dev/net/tun
        ports:
            - "83:8080"       # qBittorrent Web UI (mapped to port 83)
            - "6881:6881/tcp" # Torrent TCP port
            - "6881:6881/udp" # Torrent UDP port
        volumes:
            - /home-server-data/GluetunVpn/config:/gluetun
        environment:
            - VPN_SERVICE_PROVIDER=private internet access
            - OPENVPN_USER=${OPENVPN_USER}
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
            - SERVER_REGIONS=${OPENVPN_REGION}

    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        network_mode: "service:vpn" # Route traffic through the VPN container
        depends_on:
            - vpn
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - WEBUI_PORT=8080
        volumes:
            - /home-server-data/QBittorrent/config:/config
            - /home-server-data/downloads:/downloads
        restart: unless-stopped

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        depends_on:
            - qbittorrent  # Ensure Radarr starts after qBittorrent
        ports:
            - "84:7878"  # Radarr Web UI exposed on port 84
        volumes:
            - /home-server-data/Radarr/config:/config
            - /home-server-data/downloads:/downloads  # Shared downloads folder with qBittorrent
            - /home-server-data/Contents:/media  # Shared media folder for movie storage(eg. Jellyfin)
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
        restart: unless-stopped