name: Downloaders

services:
    vpn:
        image: qmcgaw/gluetun
        container_name: vpn
        restart: unless-stopped
        cap_add:
            - NET_ADMIN # This needed for vpn to modify network traffic
        devices:
            - /dev/net/tun
        volumes:
            - /home-server-data/downloaders/gluetunVpn/config:/gluetun
        environment:
            - VPN_SERVICE_PROVIDER=private internet access
            - OPENVPN_USER=${OPENVPN_USER}
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
            - SERVER_REGIONS=${OPENVPN_REGIONS}
        ports:
            - "8080:8080"     # qBittorrent Web UI on port 8080
            - "6881:6881/tcp" # Torrent TCP port
            - "6881:6881/udp" # Torrent UDP port
            - "9696:9696" # Prowlarr Web UI exposed on port 9696
            - "7878:7878" # Radarr Web UI exposed on port 7878
            - "6767:6767"  # Bazarr Web UI on port 6767

    qbittorrent: #torrent downloader used by prowlarr and radarr
        image: qbittorrentofficial/qbittorrent-nox
        container_name: qbittorrent
        restart: unless-stopped
        network_mode: "service:vpn" # Route traffic through the VPN container
        depends_on:
            - vpn
        environment:
            - WEBUI_PORT=8080
        volumes:
            - /home-server-data/downloaders/qBittorrent/config:/config
            - /home-server-data/Contents/downloads:/downloads

    prowlarr: # for managing indexes and searching contents
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        depends_on:
            - vpn
            - qbittorrent
        network_mode: "service:vpn" # Route traffic through the VPN container
        volumes:
            - /home-server-data/downloaders/prowlarr/config:/config
        restart: unless-stopped

    radarr: # for managing+downloading movies with pre-specified quality,size etc.
        image: linuxserver/radarr
        container_name: radarr
        depends_on:
            - vpn
            - qbittorrent
        network_mode: "service:vpn" # Route traffic through the VPN container
        volumes:
            - /home-server-data/downloaders/radarr/config:/config
            - /home-server-data/Contents/downloads:/downloads  # Shared downloads folder with qBittorrent
            - /home-server-data/Contents/movies:/media  # Shared media folder for movie storage(eg. Jellyfin)
        restart: unless-stopped

    bazarr: # for downloading subtitles
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        depends_on:
            - vpn
            - qbittorrent
            - radarr
        network_mode: "service:vpn"
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /home-server-data/downloaders/bazarr/config:/config
        restart: unless-stopped