version: '3.8'
name: AdGuardHome

services:
    AdGuardHome:
        image: adguard/adguardhome
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "81:80/tcp"
            - "3000:3000/tcp"
        volumes:
            - /home-server/AdGuardHome/config:/opt/AdGuardHome/conf
            - /home-server/AdGuardHome/work:/opt/AdGuardHome/work
        environment:
            - TZ=Europe/Berlin