name: AdGuardHome

services:
    AdGuardHome:
        image: adguard/adguardhome
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 81:80/tcp
            - 3000:3000/tcp
        volumes:
            - config:/opt/AdGuardHome/conf
            - /work:/opt/AdGuardHome/work
        environment:
            - TZ=Europe/Berlin

volumes:
    config:
        driver: local
    work:
        driver: local