name: Jellyfin

services:
    jellyfin:
        image: jellyfin/jellyfin:latest
        container_name: jellyfin
        environment:
            - TZ=Europe/Berlin
        ports:
            - "82:8096"
        volumes:
            - /home-server-data/jellyfin/config:/config
            - /home-server-data/contents:/media
        restart: unless-stopped