services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        restart: unless-stopped
        volumes:
            - /home-server-data/vaultwarden/data/:/data/
        ports:
            - 192.168.178.2:54:80 # only works with localhost if not https